version: '3.8'

services:
  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "8081:8081"
 #   environment:
  #    - SPRING_PROFILES_ACTIVE=dev
  #  restart: unless-stopped
    networks:
      - New-ecommerce-network

networks:
  New-ecommerce-network:
    driver: bridge